import 'bootstrap/dist/css/bootstrap.min.css';
import AppBar from './compoents/AppBar';
import Footer from './compoents/Footer';
import 'aos/dist/aos.css';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {



  return (
    <html lang="en">
      
      <body style={{ fontFamily: 'Poppins, sans-serif' }}>
      
      <AppBar />
       <div style={{marginTop:'160px'}}>
        {children}
        </div>
        <br/>
        <br/>
        <Footer />
      </body>
      
    </html>
  );
}
